version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    build: .
    environment:
      MAX_GOROUTINES: 10
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: "secure_pass_here"
      DATABASE_DB_NAME: testingdb
    ports:
      - "8080:8080"
    depends_on:
      - db